### ISSUE TITLE
A few more substitutions in the content json files need to be changed I think. 

### ISSUE THREAD

**Issue by fordcrews** [s0p4L1n3/Graylog_Content_Pack_Windows_Security#1]
192.168.1.1 and graylog.lab.lan need to be changed to point to your graylog server, before importing it, otherwise you have to change it in a lot of spots in graylog. 

Also maybe clarify the svr* needs to be change as well as srvad1/srvad2 , I thought svr* was referring to srvad1/2, and missed the svr* in the .json file which broke a lot of stuff.

**Comment by s0p4L1n3** [comment]
Thanks for noticing, I forgot that !  I have updated the README and the .json files.
